---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: savsmith-test-pvc
  labels:
    username: savsmith
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
