version: "3"

services:
   gen-anim:
        image: savsmith/midterm:1.0
        volumes:
            - . :/data
        user: "869411:816966"
        command: generate_animals.py /data/animals.json
   web:
        build: .
        container_name: savsmith-web
        ports:
           - 5029:5000
        volumes:
           - ./data/animals.json:/animals.json
   redis:
        image: redis:latest
        container_name: savsmith-redis
        ports:
            - 6409:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
