---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw05-deployment
  labels:
    app: hello-app
    greeting: "personalized"
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hellos
          image: ubuntu:18.04
          env:
            - name: NAME
              value: "Savannah"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ['sh', '-c', 'echo "Hello, $NAME from IP $POD_IP!" && sleep 3600']
